--TABEL USERLIST
CREATE TABLE USERS(
    USER_ID SERIAL PRIMARY KEY ,
    USERNAME VARCHAR(20),
    PASSWORD VARCHAR(255),
    EMAIL VARCHAR(50)
);

CREATE TABLE TOKO(
    TOKO_ID SERIAL PRIMARY KEY ,
    USER_ID INT,
    NAMA_TOKO VARCHAR(20),
    CONSTRAINT FK_TOKO FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE PRODUK(
    TOKO_ID INT,
    PRODUK_ID SERIAL PRIMARY KEY ,
    NAMA_PRODUK VARCHAR(20),
    CONSTRAINT FK_PRODUK FOREIGN KEY(TOKO_ID) REFERENCES TOKO(TOKO_ID)
);

CREATE TABLE CART(
    USER_ID INT,
    PRODUK_ID INT,
    QTY INT,
    CONSTRAINT FK_CART1 FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_CART2 FOREIGN KEY(PRODUK_ID) REFERENCES PRODUK(PRODUK_ID)
);

CREATE TABLE WISHLIST(
    USER_ID INT,
    WISH_ID SERIAL PRIMARY KEY ,
    PRODUK_ID INT,
    CONSTRAINT FK_WISHLIST1 FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_WISHLIST2 FOREIGN KEY(PRODUK_ID) REFERENCES PRODUK(PRODUK_ID)
);